// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jypkimmyvsvrjxgxuuwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5cGtpbW15dnN2cmp4Z3h1dXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjYwMzEsImV4cCI6MjA3Mzk0MjAzMX0.a8tjH9Y-R_eo3LhWZsbzH6MwjmlhvYAZdnyGygVl_HM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});